
import org.optaplanner.core.api.score.buildin.hardmediumsoft.HardMediumSoftScoreHolder;

import java.util.Set;

import domain.Alocacao
import domain.Disciplina
import domain.Endereco
import domain.Horario
import domain.PreRequisito
import domain.Professor

global HardMediumSoftScoreHolder scoreHolder;

rule "Disciplinas do mesmo período não podem estar alocadas no mesmo horário"

    when
        $h: Horario()
        $total: Number( intValue > 1 )
                from accumulate( Alocacao(horario == $h, $incrementar: 1) , sum($incrementar))

    then
        scoreHolder.addHardConstraintMatch(kcontext, -1);
        System.out.println("Buscando solução...");

end