
import org.optaplanner.core.api.score.buildin.hardmediumsoft.HardMediumSoftScoreHolder;

import java.util.Set;
import java.util.ArrayList;

import domain.Allocation
import domain.Subject
import domain.Schedule
import domain.PreRequisite
import domain.Teacher


global HardMediumSoftScoreHolder scoreHolder;

rule "Disciplinas do mesmo período não podem estar alocadas no mesmo horário"

    when
        // Opção 1 funcionando.
        $a: Allocation() // armazena todas as alocacoes existentes

        Allocation($subject: subject, $period: subject.period, $schedule : schedule) //

        exists (
            Allocation(
                subject != $subject,
                subject.period == $period,
                schedule == $schedule
            ) from $a
        )

        //Opção 2 funcionando.
        /*$schedule: Schedule()
        $total: Number( intValue > 1 )
                from accumulate( Allocation($schedule == schedule),
                                 init( int total = 0; ),
                                 action( total += 1; ),
                                 result( total ) )*/

    then
        scoreHolder.addHardConstraintMatch( kcontext, -1 );

    end


rule "Um teacher nao pode ter um intervalo maior ou igual a tres horas entre dois schedules de aula"

    when

        $a : Allocation()

        Allocation($teacher : teacher, $schedule : schedule != null, $subject : subject)

        // Verificando se existe alguma subject de um determinado teacher alocada antes de outra subject
        // desse mesmo teacher em um determinado dia.
        exists (
            Allocation(
                teacher == $teacher,
                schedule.diaSemana == $schedule.diaSemana,
                subject != $subject,
                schedule.horaInicio > $schedule.horaFim
            ) from $a
        )

        // Verificando nao existe um intervalo de 3 horas entre duas disciplinas de um teacher em um mesmo dia.
        // Se verdadeiro, entao a regra foi quebrada.
        not (
            Allocation(
                teacher == $teacher,
                schedule.diaSemana == $schedule.diaSemana,
                subject != $subject,
                schedule.horaInicio > $schedule.horaFim,
                (schedule.horaInicio - $schedule.horaFim) < 3
            ) from $a
        )

    then
        scoreHolder.addHardConstraintMatch( kcontext, -1 );
    end


rule "Um teacher nao pode estar alocado em schedules conflitantes"

    when

        $a : Allocation($teacher : teacher, $schedule : schedule != null)

        // Verificando se existe mais de uma allocation de um teacher em que os schedules sao iguais.
        $total : Number( intValue > 1 )
                    from accumulate(
                        Allocation(
                            schedule != null,
                            teacher == $teacher,
                            schedule == $schedule
                        ),
                        init( int total = 0; ),
                        action( total += 1; ),
                        result( total )
                    )

    then
        // System.out.println("Teacher - > " + $teacher.getNome() + " | Schedule -> " + $schedule.getStrDiaSemana() + " " + $schedule.getInitSchedule());
        scoreHolder.addHardConstraintMatch( kcontext, -1 );
    end